// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjX9rAiIl0B92BiNEk1ZrUaxNNMUqsQ_g',
    appId: '1:503013545287:android:b85e18c4252b578b836862',
    messagingSenderId: '503013545287',
    projectId: 'beetravel-tms',
    storageBucket: 'beetravel-tms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK-wA8-JnJzKrdTntmOSUQZcnuY4pUvmY',
    appId: '1:503013545287:ios:b86a846bd1fa2d5d836862',
    messagingSenderId: '503013545287',
    projectId: 'beetravel-tms',
    storageBucket: 'beetravel-tms.firebasestorage.app',
    iosBundleId: 'com.example.twsApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjX9rAiIl0B92BiNEk1ZrUaxNNMUqsQ_g',
    appId: '1:503013545287:web:b85e18c4252b578b836862',
    messagingSenderId: '503013545287',
    projectId: 'beetravel-tms',
    authDomain: 'beetravel-tms.firebaseapp.com',
    storageBucket: 'beetravel-tms.firebasestorage.app',
  );
}
