name: user_tws
<<<<<<< HEAD
description: "Bambare Travel Management System"
=======
description: "BeeTravel - Bambare Travel Management System"
>>>>>>> a28bf1f775365ea426a204b88ca42cc04604a505
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4
  google_fonts: ^6.2.1
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.3
  smooth_page_indicator: ^1.1.0
  file_saver: ^0.2.14
<<<<<<< HEAD
  path_provider: ^2.1.5
  media_store_plus: ^0.1.3
=======
>>>>>>> a28bf1f775365ea426a204b88ca42cc04604a505
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  phone_numbers_parser: ^9.0.21
  intl_phone_field_v2: ^4.0.5
  pdf: ^3.12.0
<<<<<<< HEAD
  speech_to_text: ^7.0.0
  url_launcher: ^6.3.2
=======
>>>>>>> a28bf1f775365ea426a204b88ca42cc04604a505

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/
<<<<<<< HEAD
    - images/main/
=======
>>>>>>> a28bf1f775365ea426a204b88ca42cc04604a505
    - images/home/
    - images/booking/Activity/
    - images/booking/Activity Background img/
