// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjpRfTGA4QO8iiRPi9RS4aWv1dAM7yQOI',
    appId: '1:36981082575:web:0a50d5e4a3673db085eaba',
    messagingSenderId: '36981082575',
    projectId: 'bambare-14a12',
    authDomain: 'bambare-14a12.firebaseapp.com',
    storageBucket: 'bambare-14a12.firebasestorage.app',
    measurementId: 'G-L082STTGN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5J4NlweaXWhL8hjLf0nBlQnfWE9eBTCo',
    appId: '1:36981082575:android:34866783532274d485eaba',
    messagingSenderId: '36981082575',
    projectId: 'bambare-14a12',
    storageBucket: 'bambare-14a12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBArVLDDguFoxggueVfPRcC4bmpsSVI_fk',
    appId: '1:36981082575:ios:f770f363d3e5c32e85eaba',
    messagingSenderId: '36981082575',
    projectId: 'bambare-14a12',
    storageBucket: 'bambare-14a12.firebasestorage.app',
    iosClientId: '36981082575-f7057g1tl0ul7tl5j60abg1omv5kt9ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.userTws',
  );
}
